name: Build & test

on:
  push:
    branches:
      - 'master'
  pull_request_target:
    branches:
      - 'master'

jobs:
  php:
    name: PHP test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4']
    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, dom, simplexml
          tools: wp
      - uses: actions/checkout@v2
        with:
          path: advent-of-code-2021/
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Debugging
        run: |
          php --version
          php -m
          composer --version
          ls -lsah
      - name: Composer build
        run: |
          cd advent-of-code-2021/
          composer install --prefer-dist --no-suggest
      - name: test:composer
        run: |
          cd advent-of-code-2021/
          composer run test:composer
      - name: test:phpcs
        run: |
          cd advent-of-code-2021/
          composer run test:phpcs
